### ISSUE TITLE
non empty account found

### ISSUE THREAD

**Issue by cc2200** [Land3r/Ethersecret-scanner#2]
I used the program and found a few accounts that were "non-empty."  When i went to check the etherscan link and type the private key on myetherwallet, both showed a zero balance and no transactions.  Why is it doing this?

Thanks

**Comment by FreshBac0n** [comment]
Hey how did you get over the "SubMain" not found in "Console Application" error?
Already got a SubMain, just can't seem to get over that error.

**Comment by cc2200** [comment]
the programs a waste of time, i had it running with multiple windows and apparently stumbled upon 5 or 6 "non-zero" accounts.  Only problem is all of those accounts had nothing in them.  

Waste of time

**Comment by TheRevoltingBlob** [comment]
I have the below stats but all of the accounts are empty and time stamps on the "found" keys appears to be off as well.  Nicolas,  are you seeing the same issues?

![image](https://user-images.githubusercontent.com/34888695/34698575-cd1a564c-f4a6-11e7-82f9-f4547f9417bf.png)

![image](https://user-images.githubusercontent.com/34888695/34698580-d9b8ef94-f4a6-11e7-8714-acdc1de737d0.png)

**Comment by chouhansolo** [comment]
Hey, how do you run this file? I am new to programming so I have no idea how to run this. Can you please help me?

**Comment by chouhansolo** [comment]
Does this actually work for anyone? I have been trying to use it for past 3 days and it doesn't show anything in the Stat window. Plus, no non-zero addresses.

**Comment by cc2200** [comment]
From what i understand, the odds of actually finding a "real" non-zero account are about the same odds of picking one grain of sand out of the sahara desert.  

Dont get your hopes up if you find a green non-zero account using this application, most likely those are just planted there to get you to continue using the site.

**Comment by Land3r** [comment]
Hello,

I also have encountered some non empty account that end up being empty.
The issue may be with the Ethersecret website, which i am not affiliated with or with any underlying stack.

A friend of mine updated this software to use directly Geth to check for account balance and it also showed him some false positive.
