### ISSUE TITLE
Fixed "amout" typos in BrowserCallbackForJs.cs

### ISSUE THREAD

**Issue by TheRevoltingBlob** [Land3r/Ethersecret-scanner#4]
Fixed typo(there are three below) - "amout" should be "amount" in the  BrowserCallbackForJs.cs.  

/// <summary>
         Youpi! You found an ethereum account with some ethers.
         /summary>
         aram name="privateKey">The raw private key.</param>
        param name="publicKey">The raw publib key.</param>
         param name="**amout**">The amount of ether found.</param>
        public void foundKey(string url, string privateKey, string publicKey, string **amout**)
        {
            keyFound++;
            ILog log = LogManager.GetLogger("_____KEYFOUND_____");
            log.FatalFormat("A non empty account was found on page {0}", url);
            log.FatalFormat("A non empty account was found. PrivateKey:'{0}', PublicKey:'{1}', Amount:'{2}'", privateKey, publicKey, **amout**);

**Comment by chouhansolo** [comment]
Hey, can you please tell me how to run this code on my PC? I am new to programming and have no idea how to run this.

**Comment by Land3r** [comment]
Issue is now fixed.
Thanks for reporting the issue :)
