### ISSUE TITLE
is there a way?

### ISSUE THREAD

**Issue by cc2200** [Land3r/Ethersecret-scanner#5]
Since we have all the private keys and there corresponding addresses, is it possible to get all the keys in a list and then run a simple Ctrl+f search on the corresponding address?

I understand the amount of address there are but just wondering what the actual possibilities of doing so is.  It seems as though if we have all the keys and there addresses, this could be possible.  Thoughts?

**Comment by Land3r** [comment]
Hello,
According to 2017 statistics, Google has indexed pages in the order of magnitude of the thousands of trillion pages.
The keyspace for the keys are in the order of magnitude of the hundreds thousands of trillions of trillions of trillions of trillions of trillions of trillions of trillions of trillions keys.
So it is definetly not possible at the moment
