### ISSUE TITLE
Stops scanning

### ISSUE THREAD

**Issue by cryptonoob27** [Land3r/Ethersecret-scanner#6]
Sometimes the program will stop scanning because it won't load data from etherscan. The "loading" gif just keeps going on a loop. The problem is resolved by refreshing or going to a new random page. 

Is there a way for the program to autodetect when it's hung up and refresh automatically or set a timer for max time per page 10-15 seconds, so if it gets hung up it will refresh or go to new random page?

I seem to have found the script in question. It is Payload.js

this part that sets a timeout seems to not be working

```
 case 3:
                        if (elm.text() == "") {
                            // At least one element is not loaded.
                            // Wait for elements to load.
                            
                            if (alreadyRedirected == false) {
                                setTimeout(parseAmmout, 2000);
                            }
                            alreadyRedirected = true;
                            return;
                        }
                        else if (elm.text() != '0') {
                            golden = true;
                            foundKey(privateKey, publicKey, elm.text());
                            return;
                        }
                        break;
                }
            });
        });
        if (alreadyRedirected == false) {
            goToNextPage();
        }
    }

    function goToNextPage() {
        dotnetcallback.callNextPage();
    }

    function foundKey(privateKey, publicKey, amount) {
        dotnetcallback.foundKey(document.URL, privateKey, publicKey, amount);
    }

    setTimeout(parseAmmout, 2000);
```

Here is a screencap of an incident. I noticed it happens when there are public keys that are exactly the same generated. I don't know if this is in error. Sometimes happens every 5 minutes and sometimes it can take an hour before it happens. But it is essentially unusable if I have to sit there and manually refresh it every 5-60 minutes.

![esss](https://user-images.githubusercontent.com/37631484/37747890-8c9b6efa-2d3e-11e8-85af-b0bff93d9d01.png)

**Comment by tazmanny** [comment]
I corrected it adding a time out as you mention. 

`


                    case 3:
                        if (elm.text() == "") {
                            // At least one element is not loaded.
                            // Wait for elements to load.
                            goToNextPage();
                            return;
                        }
                        else if (elm.text() != '0') {
                            golden = true;
                            foundKey(privateKey, publicKey, elm.text());
                            return;
                        }
                        break;
                }
            });
        });
        if (alreadyRedirected == false) {
            goToNextPage();
        }
    }

    function goToNextPage() {
        dotnetcallback.callNextPage();
    }

    function foundKey(privateKey, publicKey, amount) {
        dotnetcallback.foundKey(document.URL, privateKey, publicKey, amount);
    }

    setTimeout(parseAmmout, 10000);
`
