### ISSUE TITLE
Resource Limit Is Reached The website is temporarily unable to service your request as it exceeded resource limit. Please try again later.

### ISSUE THREAD

**Issue by arber1337** [Land3r/Ethersecret-scanner#8]
this 508 error is killing the scanner app, do you have a solution (script) to autoreload the ethersecret site ?
because the scann stop when it show this message. and thnx for this project.

**Comment by band1k1** [comment]
I have the same error.

**Comment by donMiki** [comment]
Hello there. 
Is that possible to run the scanner on a Other Website? 
I have found a similarly site http://eth.pkeybase.com!

Many thanks
